# Generated by Django 4.2.3 on 2023-08-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(help_text="True meant Man's sex and False is Woman")),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('size', models.SmallIntegerField()),
                ('more', models.TextField()),
                ('category', models.ManyToManyField(to='Warehouse.category')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.sex')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('imported_time', models.DateTimeField(auto_now_add=True)),
                ('exported_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.productinfo')),
            ],
        ),
    ]
