# Generated by Django 4.2.3 on 2023-08-07 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10, unique=True)),
                ('sex_persian', models.CharField(help_text='please enter sex name in persian/لطفا جنسیت را به فارسی تایپ کنید.', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('size', models.SmallIntegerField()),
                ('more', models.TextField()),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='Warehouse.category')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Maximum rate number is 5.'), django.core.validators.MinValueValidator(1, 'Minimum rate number is 1.')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=1)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='Warehouse.productinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('imported_time', models.DateTimeField(auto_now_add=True)),
                ('exported_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.productinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product_info')},
            },
        ),
    ]
