# Generated by Django 4.2.3 on 2023-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
