# Generated by Django 4.2.3 on 2023-08-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_productcomment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.productinfo'),
        ),
    ]
