# Generated by Django 4.2.3 on 2023-08-06 12:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Warehouse', '0003_alter_like_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rate',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Maximum rate number is 5.'), django.core.validators.MinValueValidator(1, 'Minimum rate number is 1.')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'product_info')},
        ),
    ]
