# Generated by Django 4.2.3 on 2023-08-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0004_alter_productcomment_rate_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='product_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Warehouse.productinfo'),
        ),
    ]
