# Generated by Django 4.2.3 on 2023-08-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_productcomment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='image',
        ),
    ]
