# Generated by Django 4.2.3 on 2023-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0006_remove_productcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=1, null=1, upload_to='Media/uploded/'),
            preserve_default=1,
        ),
    ]
