# Generated by Django 4.2.3 on 2023-08-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0007_alter_productcomment_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='Warehouse.productinfo'),
        ),
    ]
