# Generated by Django 4.2.3 on 2023-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0008_alter_productcomment_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
