# Generated by Django 4.2.3 on 2023-08-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0008_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
