# Generated by Django 4.2.3 on 2023-08-07 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('postalcode', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('phone', models.CharField(help_text='Insert Like 0930***2905/مانند روبرو وارد کنید', max_length=11, validators=[django.core.validators.MinValueValidator(10)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
