# Generated by Django 4.2.3 on 2023-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
