# Generated by Django 4.2.3 on 2023-08-07 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Insert Like 0930***2905/مانند روبرو وارد کنید', max_length=11, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
