# Generated by Django 4.2.3 on 2023-08-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=1, null=1, upload_to='Media/user uploded/'),
            preserve_default=1,
        ),
    ]
