# Generated by Django 4.2.3 on 2023-08-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('imported_time', models.DateTimeField(auto_now_add=True)),
                ('exported_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productinfo')),
            ],
        ),
    ]
