# Generated by Django 4.2.3 on 2023-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.ManyToManyField(to='Products.category'),
        ),
    ]
