# Generated by Django 4.2.3 on 2023-08-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='sex',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Products.sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='size',
            field=models.SmallIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
